### ISSUE TITLE
Suggestion: Trispec sors? :)

### ISSUE THREAD

**Issue by bobzen1234** [theBGuy/Kolbot-SoloPlay#10]
Hey again. Trying out a sorc and wanted to ask if u can add  trispec sorc? that way it can do hell runs without running into too many problems with immune mobs or maybe you can suggest me a build thats already in the bot that wont have too much problems with immune mobs? :)

trying the blizzballer atm in singleplayer to see if it can run without skipping too many mobs due to immunity :)

**Comment by theBGuy** [comment]
The leveling build for the sorc is fine to take it all the way through hell. Any of the final builds for the sorceress can handle hell, although my personal choice is always a lightning sorceress for the infinity runeword.

**Comment by bobzen1234** [comment]
> The leveling build for the sorc is fine to take it all the way through hell. Any of the final builds for the sorceress can handle hell, although my personal choice is always a lightning sorceress for the infinity runeword.

Yea true i guess i will try lightning out aswell :)
Thanks for the tip :)
