### ISSUE TITLE
Bone spear not trigger in latest version.

### ISSUE THREAD

**Issue by ly19811105** [theBGuy/Kolbot-SoloPlay#12]
The Latest version use necromancer bone spear looks like always not trigger when I run leveled to 21.but Teeth is ok. Please help on this.thanks.
--Sorry, this should be the cast effect is not visible in the game. Is there anyway to visible the cast effect?

Config.AttackSkill = [-1, 84, -1, 84, -1, -1, -1]; LV21  get from this path :kolbot-master\d2bs\kolbot\libs\config\Builds\Necromancer.Start.js

**Comment by FNCardascia** [comment]
In the FAQ..

Q: HELP!!! The bot isn't casting any skills!

A: The bot uses packet casting for stability, which doesn't show the casting animations. It is actually casting the skills, if you would like to see the casting animations you will need to navigate to libs\SoloPlay\Tools\Developer.js and change forcePacketCasting.enabled to false.

**Comment by ly19811105** [comment]
Thanks a lot.

**Comment by theBGuy** [comment]
Was that sarcasm?
