### ISSUE TITLE
Assassin attack issue

### ISSUE THREAD

**Issue by Osandai** [theBGuy/Kolbot-SoloPlay#14]
![image](https://user-images.githubusercontent.com/90568584/132995597-338c93b5-443e-4545-9236-bd39b05d15d7.png)

Having issues creating a working bot for asssassin getting the attached message.
Bot standing in town without starting.

Thank you

**Comment by theBGuy** [comment]
hello, please grab the update I just did. I had left out the include for the assasin overrides which was causing the issue

**Comment by Osandai** [comment]
Thank you for the quick response! I'll do that.

Awesome work!

**Comment by Osandai** [comment]
Can confirm change working!
