### ISSUE TITLE
<SCL-PAL> Pickit Tier (Merctier) error! Line # 1 Entry: undefined (Kolbot-SoloPlay) Error message: buildWeights is not defined

### ISSUE THREAD

**Issue by FNCardascia** [theBGuy/Kolbot-SoloPlay#15]
Fresh install of most recent commit. Message is spammed in console when shopping

**Comment by theBGuy** [comment]
Thank you for bringing this to my attention, please try the update I just pushed. I had a typo when adding the ctc tier scores for the merc

**Comment by FNCardascia** [comment]
Appreciate it. Checking it out now

**Comment by FNCardascia** [comment]
Looks good so far! TY! Will close for now unless something else pops up
