### ISSUE TITLE
Auto drop the currently equiped when find better one on minishopbot processing.

### ISSUE THREAD

**Issue by ly19811105** [theBGuy/Kolbot-SoloPlay#16]
I know you have been set the junk.sell() function to control these junk items. But this drop issue happened in auto equip phase and already dropped before inventor clear function. So currently junk.sell() function not handled these items because of them are not in character's bag. Maybe this is not a big problem, but it is a big waste in the early stage of the game, especially in low gold  phase. Could you please help set don't drop them?

**Comment by theBGuy** [comment]
I keep items during the autoequip process to sell if there is room for them and if they are worth more than 1000 gold per square, or in other words worth selling. I haven't seen any of the bots have gold issues, but I could test with scaling what items need to be worth to keep. I'll consider this.

**Comment by theBGuy** [comment]
Tested and confirmed. I updated this so more of the items will be sold early on and it scales with difficulty
