### ISSUE TITLE
Sorceress Starter Issue?

### ISSUE THREAD

**Issue by FNCardascia** [theBGuy/Kolbot-SoloPlay#19]
Haven't messed around with leveling one since implementation of the stepping stone logic. Seems to act up once she hits mid 20s. Does nothing but teleport and static attack-wise.

**Comment by aim2kill** [comment]
Are you sure? packetcast you wont be able to see skills use. Look at the skill in the right/left if they changes other the teleport and static

**Comment by FNCardascia** [comment]
Yeah, positive. She's running to Tristram because of no money and getting punched to death by Griswold. I created a new character right at the start of opening this issue and fell asleep so I could provide some log info. Here is what I have from roughly 12 hrs of runtime:

{"runs":27,"experience":1375102,"deaths":0,"lastArea":"Tristram","gold":94,"level":24"gameName":"","ingameTick":277895093,"handle":1443196,"currentBuild":"Start","debugInfo":"{\"area\":\"Stony Field\",\"currScript\":\"no entry\"}","finalBuild":"Lightning"}

Script performance data:

04:45:35,04:01:19,00:25:36,templeruns,21,271528,10606.990646757877,Normal,63,16,28,5,Start
04:48:33,04:04:17,00:02:58,eye,21,20487,6910.0005621451455,Normal,67,16,28,55,Start
04:49:56,04:05:40,00:01:23,heart,21,6844,4926.103646833014,Normal,67,16,28,55,Start
04:53:48,04:09:32,00:03:52,brain,21,52690,13620.324933544154,Normal,67,16,28,5,Start
05:00:19,04:16:03,00:06:31,travincal,22,31297,4806.640864971127,Normal,67,16,28,5,Start
05:16:10,04:31:32,00:13:10,tombs,22,137668,10449.805364771846,Normal,76,16,19,5,Start
05:18:26,04:33:48,00:02:16,travincal,22,21532,9521.25464300454,Normal,76,16,19,5,Start
05:22:18,04:37:40,00:03:52,mephisto,22,12744,3297.6388140161725,Normal,76,66,19,55,Start
05:39:20,04:54:21,00:14:40,tombs,23,147241,10044.146922960606,Normal,76,16,19,5,Start
05:42:41,04:57:42,00:03:21,travincal,23,24500,7309.432648799165,Normal,76,16,19,5,Start
05:47:39,05:02:39,00:04:56,mephisto,23,28668,5812.003933056938,Normal,76,66,19,55,Start
05:51:53,05:06:54,00:04:14,izual,24,56599,13356.69616519174,Normal,151,66,19,55,Start
06:01:29,05:16:08,00:04:02,travincal,24,7000,1737.1092021291995,Normal,76,16,19,5,Start
06:05:03,05:19:42,00:03:34,mephisto,24,796,223.61853748981636,Normal,76,66,19,55,Start
06:07:31,05:22:10,00:02:28,izual,24,3121,1263.8015279539995,Normal,76,141,19,55,Start
06:17:44,05:26:28,00:04:17,travincal,24,3500,818.6623836329896,Normal,76,16,19,5,Start
06:24:50,05:33:35,00:07:06,mephisto,24,28166,3967.917803458979,Normal,76,66,19,55,Start
06:28:56,05:37:40,00:04:06,izual,24,8958,2185.5710347183253,Normal,76,66,26,55,Start

Leveling performance data:

04:38:16,03:54:00,00:13:00,Forgotten Reliquary,21,136305,10484.368249605473,Normal,63,16,103,5,Start
04:56:52,04:12:36,00:18:36,Travincal,22,169413,9111.034225603591,Normal,67,16,28,5,Start
05:23:50,04:39:12,00:26:58,City Of The Damned,23,210919,7821.997897262548,Normal,151,66,19,55,Start
05:51:15,05:06:16,00:27:26,Plains Of Despair,24,262713,9579.232289445985,Normal,151,66,19,55,Start

**Comment by theBGuy** [comment]
Can you confirm that you've updated all files, the stepping build wouldn't take affect until level 26 and from the data you are still on the start build. If its a gold issue, it should be solved by the last update I did which is selling more of the autoequip junk.

**Comment by FNCardascia** [comment]
Yeah, I can confirm it's a fresh install. Every release I wipe everything. I might just try an older commit to at least help pin-point when the issue popped up. Just haven't had time to test it since that new change.

**Comment by FNCardascia** [comment]
Well, I can least debunk the new logic breaking it. 399 is causing the same issue. So it may have something to do with having no money then?

**Comment by theBGuy** [comment]
Hmm, is it out of mana potions too? I'm surprised that it managed to run out of gold I haven't seen a sorc break since I added the minimum gold requirement to shop items.

**Comment by FNCardascia** [comment]
Yep, out of potions and couple pieces of equipment almost broken.
