### ISSUE TITLE
Using script with existing character

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#27]
Hi,

I pointed the bot to use an older character I had 91 summon necro with enigma and set summon spec but he doesnt use summons just golem and merc how can I make it detect my level or force it to use the spec I want?

**Comment by theBGuy** [comment]
The script really isn't designed to be used with an existing character for many reasons, different skills, stats, chance to lose gear, ect. However to force it to use a spec, first you need to ensure you meet the finalBuild requirements. Which for a summon necro on expansion is an Enigma. Second, either let it respec itself if you have one available or after the datafile is created open it and change currentBuild to the set finalBuild then restart and it should load up using the finalBuild in the next game

**Comment by ForestRock22** [comment]
Thanks for the info
