### ISSUE TITLE
Stuck at start of a3 hell with potion <in hand>

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#30]
Hi, 

I mention the potion because that might be part of the issue?

The overlay is not started so the game wont timeout and he was stuck there all night.

Error this.desc is undefined in prototypeoverrrides.js:739

![image](https://user-images.githubusercontent.com/21211675/139277150-602adf08-1906-44ff-a735-0c26e7d76de8.png)

**Comment by theBGuy** [comment]
No response since update so I am going to close this out
