### ISSUE TITLE
Failed to make TP

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#31]
Character keeps making TP over and over then eventually errors out

![image](https://user-images.githubusercontent.com/21211675/139470552-5fafc4a2-094a-4897-a340-aa1c4347c7d4.png)

**Comment by theBGuy** [comment]
Can you give more information? Did it ever go through the tp or did it just spam it until none were left and error out?

**Comment by ForestRock22** [comment]
Spam until he ran out and error out of the game.

**Comment by ForestRock22** [comment]
Had a similar issue with my sorc she kept making the portal without taking it, this seems to be a Blood Raven thing havent seen it anywhere else.

![image](https://user-images.githubusercontent.com/21211675/146976766-618db25f-6135-4e26-a578-136ff719fdf7.png)

**Comment by theBGuy** [comment]
I've learned there's actually a getUnit bug that can occur in act 1 and 2 so I think that's what is happening with the portal spam

**Comment by ForestRock22** [comment]
Ok anyways the workaround seems to be working meaning they do get out of it somehow without exiting the game.
