### ISSUE TITLE
Blood Raven running in place

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#33]
I just updated and im seeing some issues with Blood Raven in particular.

Character just runs spins in place after <glitching> on clearing area error. This seemed to happen right after blood raven went just outside the fence. But then even after she moves back in hes still stuck.

![image](https://user-images.githubusercontent.com/21211675/139471485-d255a762-f657-4639-89b5-bc79f73ba573.png)

**Comment by theBGuy** [comment]
`PickItem :: Clearing area around item I want to pick` isn't an error. It's just saying what it's trying to do. Its trying to clear the area before running to the spot where the items it wants to pick are. I'm not sure what you mean about spinning in place though

**Comment by ForestRock22** [comment]
Usually it will say that msg once but that time it just spammed it 20x in a second and then started to walk up 1feet then down 1 feet, thats what I mean by spinning in place, moving fast in a very short area. If I catch it again ill try to capture if that helps.

**Comment by ForestRock22** [comment]
Paladin still strugling on BloodRaven, he was standing here while his merc was fighting her offscreen

![image](https://user-images.githubusercontent.com/21211675/144531756-e24463cf-d3a6-4beb-ae97-24811311a91f.png)

**Comment by ForestRock22** [comment]
Then ended up <twitching> in place 

![image](https://user-images.githubusercontent.com/21211675/144531994-957e42dd-e300-40be-83a3-c7285f7885b5.png)

**Comment by theBGuy** [comment]
Just removed the stamina pot pickup for now until I can find a better solution

**Comment by ForestRock22** [comment]
Still standing still while merc is doing the work with weird error

![image](https://user-images.githubusercontent.com/21211675/144536348-3b77b972-cff1-4677-9123-57909f761d92.png)

**Comment by ForestRock22** [comment]
With the latest versions hammerdin is doing much better here but still the weird recasting of the portal but after a many times he does take it.
