### ISSUE TITLE
Sorc ran out of gold weapon broken and not attacking so not leveling

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#34]
![image](https://user-images.githubusercontent.com/21211675/141229890-f7e81a00-a9ca-4107-9ab6-dc5f446c826b.png)

Shes running the level script but when she hits a pack of mobs then she just frost novas once and static and stands there until shes out of health and has to TP to town then does it all over again but has no gold to repair or buy potions.

**Comment by ForestRock22** [comment]
I restarted the profile and she was able to punch mobs to death, she got a few blues to sell and was able to buy potions but not repair. The main problems looks to be that since the main weapon is broken she doesnt use lightning nova at all even when she has mana she just repeats frost nova - static - wait - frost nova - wait - frost nova - wait and this process is very slow and cant kill some mobs at all. 

now shes not attacking at all after not being able to attack the Carver shaman she doesnt even nova they dont do enough damage to kill her so she will probably be standing here for hours
![image](https://user-images.githubusercontent.com/21211675/141231210-4e76fa93-9239-4885-827d-e18a8a3327dc.png)

**Comment by theBGuy** [comment]
Hm, I had hoped gold issues were done with when I added selling autoequip items. Did you happen to see where she lost all her gold at? The broken weapon shouldn't change casting so I'll be looking into that. I have been trying to find a way to dynamically use the lower mana skills on easy to kill mobs but haven't gotten it to work the way I want.

**Comment by ForestRock22** [comment]
No sorry she was already running on empty when I noticed.

**Comment by theBGuy** [comment]
Please update, this issue was actually caused by the sorc build assigning the main attack to be blizzard without having the skill yet

**Comment by ForestRock22** [comment]
Done thank you!
