### ISSUE TITLE
Stuck on select difficulty screen

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#35]
![image](https://user-images.githubusercontent.com/21211675/141342711-93906b1f-7e2f-4e87-b4f9-7c02e1b820b7.png)

Chickend out then not selecting difficulty

[11/11/21 12:23:39] D2BS 20796: ÿc2Drinking potion from inventory.
[11/11/21 12:23:40] D2BS 20796: ÿc2Drinking potion from inventory.
[11/11/21 12:23:41] D2BS 20796: ÿc1Pausing.
[11/11/21 12:23:41] D2BS 20796: Going to town
[11/11/21 12:23:41] D2BS 20796: Script default.dbj ended
[11/11/21 12:23:41] D2BS 20796: Script libs\soloplay\tools\eventthread.js ended
[11/11/21 12:23:41] D2BS 20796: Script libs\soloplay\tools\townchicken.js ended
[11/11/21 12:23:41] D2BS 20796: Script tools\autobuildthread.js ended

**Comment by theBGuy** [comment]
Added a handle for this screen location, should fix the issue. Please update your files and let me know if you still see this issue

**Comment by ForestRock22** [comment]
Will do thanks!

**Comment by ForestRock22** [comment]
I reset my character to run again and it was stuck again but this time completely frozen on the sceen. I stopped/started and it froze again. I went to DBS and switched the difficulty in the profile from Hell (I guess it was still there from the previous run) to Highest and it worked.

**Comment by theBGuy** [comment]
You should always delete the old data files when running a profile over with a new character. SoloCleaner makes this easy to do if you set it up. However I'll look to see if I can set up an error handler for this situation

**Comment by theBGuy** [comment]
Can you give me a little more info on the steps to this? My understanding is

you ran a profile until you were done with that character-> restarted that profile with a new character (was this character already made or created by the script) -> it ran fine until it beat baal in normal and was faced with the select difficulty screen. 

Did you delete the old data files with that profile before running it again?

**Comment by ForestRock22** [comment]
I ran the d2botsolocleaner script but did not change the difficulty, it was left set to hell, it was able to start but then when it came to changing over to nightmare its blocked.

I tried it again today and it worked for my sorc but not the other classes does that make sense?

I think I got around it with using <highest> as the setting.

**Comment by theBGuy** [comment]
Hopefully have this settled now. If you use a profile over as long as the old data file has been deleted it will always initialize to normal
