### ISSUE TITLE
Beginning act2 routine slow

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#37]
Character loaded in a2 and was just sitting in the west area of town for a few minutes feels like some kind of pathing issue

![image](https://user-images.githubusercontent.com/21211675/142858408-dc136218-4d4f-42f5-8f6b-abb8b3484a6f.png)

**Comment by theBGuy** [comment]
Was this after a crash?

**Comment by ForestRock22** [comment]
Not sure, it wasnt the first time I notice this behaviour of a character running around the west side of a2.

**Comment by theBGuy** [comment]
Yeah I've seen it as well but only after a crash. I think it's a d2bs issue but not entirely sure why it seems to fail to load the town map

**Comment by ForestRock22** [comment]
Ah ok that makes sense ill keep an eye out and let you know.
