### ISSUE TITLE
Stuck on Clearing to pickup

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#38]
New character just got stuck there until the profile restarted (only a couple mins)

![image](https://user-images.githubusercontent.com/21211675/144172162-a62d43ac-9a36-4166-85c5-0273bbbc502a.png)

**Comment by theBGuy** [comment]
Stuck as in wasn't attacking?

**Comment by ForestRock22** [comment]
The only item in view was a stamina potion near the shaman on the left

**Comment by theBGuy** [comment]
This shouldn't happen anymore, I added a monster count check before attempting to pick up the stamina potion. I'm also trying to work on a better solution to instead keep 1 or 2 stamina pots in the inventory similar to the health/mana pots buffer
