### ISSUE TITLE
Druid ran out of gold cant buy mana potions not attacking

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#39]
Not enough gold to buy merc and only buys a few potions at a time as little gold he has. Hes using mana regen to cast tornado but no other attacks.

![image](https://user-images.githubusercontent.com/21211675/144235538-a8889104-22a3-482b-8508-92618def3e72.png)

**Comment by ForestRock22** [comment]
Maybe not hiring merc below a certain level of gold could lower these issues?

**Comment by theBGuy** [comment]
Possibly, he should at least attack now. I'll experiment a bit with the merc to figure out at what point he's just draining gold
