### ISSUE TITLE
Javzon config attack

### ISSUE THREAD

**Issue by RickerMD** [theBGuy/Kolbot-SoloPlay#4]
could you help me on a light javazon attack config?

/* Attack config
	 * To disable an attack, set it to -1
	 * Skills MUST be POSITIVE numbers. For reference see ...\kolbot\sdk\skills.txt
	 */
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 24; // Primary skill to bosses.
	Config.AttackSkill[2] = 24; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 35; // Primary skill to others.
	Config.AttackSkill[4] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

// Class specific config
	Config.LightningFuryDelay = 10; // Lightning fury interval in seconds. LF is treated as timed skill.
	Config.SummonValkyrie = true; // Summon Valkyrie

ty

**Comment by theBGuy** [comment]
This isn't really a GuysSolo issue, but Whats your issue? The basic set up you have would work except i'd lower the LightningFuryDelay down to 1 second. I will note that basic Kolbots amazon doesn't work very well without modifications to its attack file

**Comment by RickerMD** [comment]
> This isn't really a GuysSolo issue, but Whats your issue? The basic set up you have would work except i'd lower the LightningFuryDelay down to 1 second. I will note that basic Kolbots amazon doesn't work very well without modifications to its attack file

Its kind akward the way its working.
what should i modify on attack file?

**Comment by RickerMD** [comment]
i wnow, but there is a desert there to get support.
