### ISSUE TITLE
Skiped Malus with struct warning

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#41]
![image](https://user-images.githubusercontent.com/21211675/144737604-8a4d8a28-fed7-400c-9dd8-02d1e83422b0.png)

**Comment by ForestRock22** [comment]
Typo in Hoardric

**Comment by theBGuy** [comment]
Ty, just fixed this. I don't know why I always swap the r and the a in horadric
