### ISSUE TITLE
Failed to move to ancients altar

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#43]
![image](https://user-images.githubusercontent.com/21211675/145662805-6347d7cd-aff6-47e5-800f-a228d78b869b.png)

**Comment by ForestRock22** [comment]
The portal is to the middle of the frozen thundra

**Comment by ForestRock22** [comment]
Just had a look at his inventory and its full of potions not sure how that happened 
![image](https://user-images.githubusercontent.com/21211675/145662879-fc7c10ef-bd7d-474a-8dda-db1714fb1e4a.png)

**Comment by theBGuy** [comment]
Can you send me the whole log file?

**Comment by theBGuy** [comment]
I think it failed to get the waypoint then proceeded on with the rest of the ancients script, I just pushed an update to handle this
