### ISSUE TITLE
Gear evaluation +skill for other classes

### ISSUE THREAD

**Issue by ForestRock22** [theBGuy/Kolbot-SoloPlay#48]
Hi,

It looks like the gear evaluation might be considering other +skill classes wrongly? Maybe its just for necro?

For example my necro is using a pair of gloves with +3 amazon, I would expect by that level that he would use something with +res or other, same thing for his amulet +3 paladin

![image](https://user-images.githubusercontent.com/21211675/147389004-1db3023e-75e7-4c04-931f-23ced74078ea.png)
![image](https://user-images.githubusercontent.com/21211675/147389014-a3bf9d34-d9d4-4702-b9c4-16a18d56b120.png)

**Comment by theBGuy** [comment]
Can you print the tier value of both? I haven't seen that be an issue before

**Comment by ForestRock22** [comment]
> Can you print the tier value of both? I haven't seen that be an issue before

How do I do that? When I try to use keypad 6 it only logs item in inventory not equiped.

**Comment by theBGuy** [comment]
Hover over the item and press numpad decimal. It will print the item info to the console

**Comment by ForestRock22** [comment]
I unequipped them as well to get the info in d2bs as well.
![image](https://user-images.githubusercontent.com/21211675/147389200-1a0009b7-5d40-4566-85b6-86eeb7977a52.png)
![image](https://user-images.githubusercontent.com/21211675/147389225-8d437a52-7700-4a12-a5d7-6431b8ba63ee.png)

**Comment by theBGuy** [comment]
Hmm it seems you are right. The only way they could of gotten that high of a tier is from the skills. Thank you I'll get this fixed

**Comment by theBGuy** [comment]
Just to get a little more info, what build are you currently using?

**Comment by ForestRock22** [comment]
Summon but hes 86 and not on final build yet

**Comment by theBGuy** [comment]
I found a typo, please update and retry to see if it fixes it

**Comment by ForestRock22** [comment]
Yeah that worked he switched to another +1 he had in inventory
