### ISSUE TITLE
New Sorceress not attacking enemies (magic or physical)

### ISSUE THREAD

**Issue by FNCardascia** [theBGuy/Kolbot-SoloPlay#7]
I'm not sure if it's pertaining to the new logic in ClassAttackOverrides? Sorceress stands outside of melee range, doesn't attempt to attack and inevitably has to chicken out of the game in the Blood Moor.

**Comment by theBGuy** [comment]
Thank you, I see the issue so I'll have a fix out in a couple minutes

**Comment by FNCardascia** [comment]
Looks good initially now! Closing
