### ISSUE TITLE
bot will swap gear and get - res :(

### ISSUE THREAD

**Issue by bobzen1234** [theBGuy/Kolbot-SoloPlay#9]
Hi there

Im still running your bot and its working great so far. Got my hammerdin to 81 and going strong

However i noticed that the bot will make some strange gear replacements resulting in my hammerdin to go in - res on hell. I tried to fix it with charms but it ended up selling them seems like it will only keep up to 6 charms in inv if im not mistaking :)

other than that the bot seems to run perfectly :)

**Comment by aim2kill** [comment]
Hi. 
1.What weird gear replacement he has done?
2. Look like he over lvl and move to hell
3. Yes only 6 small charm. And manually putting stuff on him may end up selling it

**Comment by bobzen1234** [comment]
> Hi.
> 1.What weird gear replacement he has done?
> 2. Look like he over lvl and move to hell
> 3. Yes only 6 small charm. And manually putting stuff on him may end up selling it

The gear replacement was heppening in hell at around lvl 80 the bot was switching res gear for 1+ skiller gear and it ended up going - res however after it got a few lvls its running smooth again now :) hell difficulty done and farming on :)

Great job on the bot mate :)
